### ISSUE TITLE
Syntax error in SystemProcess.py

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/core9#123]
#### Installation information

- jumpscale version: master
- operating system: linux

#### Detailed description
travis.yml:
```yaml
language: python
python:
  - "3.5"
sudo: required
install:
  - pip3 install pycodestyle nose2
  - ./jumpscale_install.sh
script:
  - pycodestyle --show-source --show-pep8 --ignore=E501 zerorobot
  - nose2
```

Tried to install jumpscale in a travis job using this script:
```shell
#!/bin/bash
set -e

# Install ays9 in a docker contianer using bash installers
ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

export ZUTILSBRANCH=${ZUTILSBRANCH:-master}

curl https://raw.githubusercontent.com/Jumpscale/bash/$ZUTILSBRANCH/install.sh?$RANDOM > /tmp/install.sh;sudo -E bash /tmp/install.sh
sudo -HE bash -c "source /opt/code/github/jumpscale/bash/zlibs.sh; ZCodeGetJS"
eval $(ssh-agent)
ssh-add
sudo -HE bash -c "source /opt/code/github/jumpscale/bash/zlibs.sh; ZInstall_host_js9_full"
```

#### Steps to reproduce
use the script from the description above

#### Relevant stacktraces
```
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing top-level names to JumpScale9.egg-info/top_level.txt
    writing JumpScale9.egg-info/PKG-INFO
    writing dependency_links to JumpScale9.egg-info/dependency_links.txt
    writing requirements to JumpScale9.egg-info/requires.txt
    reading manifest file 'JumpScale9.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'JumpScale9.egg-info/SOURCES.txt'
    running build_ext
    Creating /usr/lib/python3.4/site-packages/JumpScale9.egg-link (link to .)
    Adding JumpScale9 9.2.0 to easy-install.pth file
    Installing js9 script to /usr/bin
    Installing js9_code script to /usr/bin
    Installing js9_docker script to /usr/bin
    Installing js9_docs script to /usr/bin
    
    Installed /opt/code/github/jumpscale/core9
    Running post install task
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 97, in <module>
        'cmds/js9_docs',
      File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/jumpscale/core9/setup.py", line 42, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.4/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.4/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/jumpscale/core9/setup.py", line 9, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/opt/code/github/jumpscale/core9/JumpScale9/__init__.py", line 88, in <module>
        from .sal.process.SystemProcess import SystemProcess
      File "/opt/code/github/jumpscale/core9/JumpScale9/sal/process/SystemProcess.py", line 273
        async def _read_stream(stream, cb, res):
                ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/
[-] something went wrong: Could not install core9 of js9
```

**Comment by arahmanhamdy** [comment]
I tested the script directly on a VM and works normally, Could you double check which python version is run on travis?

**Comment by arahmanhamdy** [comment]
I tested the script directly on a VM and works normally, Could you double check which python version is run on travis?

**Comment by zaibon** [comment]
https://travis-ci.org/Jumpscale/zerorobot/builds/307482624#L440
This is python 3.5.3

**Comment by ahussein** [comment]
I am going to close this ticket. the travis logs shows that the python version used to run js9 is 3.4 which doesnt support the async/await syntax.
