### ISSUE TITLE
Authorization failed in step "node.ovc"

### ISSUE THREAD

**Issue by hossamabdullah** [Jumpscale/core9#124]
#### Installation information

- jumpscale version: 9.3.0
- operating system: ubuntu 16.04

#### Steps to reproduce
using the following blueprint
```
g8client__env:
    url: 'du-conv-2.demo.greenitglobe.com'
    login: 'hossam'
    password: '<my password>'
    account: 'hossam'


vdc__vdcname:
    description: 'vdc for demo'
    g8client: 'env'
    account: 'hossam'
    location: 'du-conv-2'

disk.ovc__myDisk:
  size: 10

node.ovc__demo:
    bootdisk.size: 50
    os.image: 'Ubuntu 16.04 x64'
    disk:
      - 'myDisk'

actions:
  - action: install
```
and running the following commands
```
ays blueprint 1_test.yaml
```

```
 ays run create -f
```

#### Relevant stacktraces
```
job: node.ovc!demo (install) failed:
Traceback (most recent call last):
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 169, in _connect
    banner_timeout=3.0)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 394, in connect
    look_for_keys, gss_auth, gss_kex, gss_deleg_creds, gss_host)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 649, in _auth
    raise saved_exception
  File "/usr/local/lib/python3.5/dist-packages/paramiko/client.py", line 587, in _auth
    self._transport.auth_publickey(username, key))
  File "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py", line 1398, in auth_publickey
    return self.auth_handler.wait_for_response(my_event)
  File "/usr/local/lib/python3.5/dist-packages/paramiko/auth_handler.py", line 217, in wait_for_response
    raise e
paramiko.ssh_exception.AuthenticationException: Authentication failed.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/node.ovc/ab4713b1220da14dc4827d16b046b9fa.py", line 492, in install
    raise e
  File "/tmp/actions/node.ovc/ab4713b1220da14dc4827d16b046b9fa.py", line 481, in install
    prefab = _check_ssh_authorization(service, machine)
  File "/tmp/actions/node.ovc/ab4713b1220da14dc4827d16b046b9fa.py", line 40, in _check_ssh_authorization
    prefab = _ssh_authorize(service, vm_info)
  File "/tmp/actions/node.ovc/ab4713b1220da14dc4827d16b046b9fa.py", line 610, in _ssh_authorize
    executor.prefab.ssh.authorize("root", sshkey.model.data.keyPub)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 103, in prefab
    self._prefab = j.tools.prefab.get(self)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabFactory.py", line 83, in get
    prefab = PrefabRootClass(executor)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabRootClass.py", line 15, in __init__
    self.core = PrefabCore(self.executor, self)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabBase.py", line 11, in __init__
    self.executor.dir_paths
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 448, in dir_paths
    if self.exists(self.state.configJSPath):
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 38, in state
    self._state = State(self)
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 15, in __init__
    self.load()
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/State.py", line 20, in load
    self.configJSPath = self.executor.stateOnSystem["path_jscfg"] + \
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorBase.py", line 207, in stateOnSystem
    rc, out, err = self.execute(C, showout=False, hide=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/executor/ExecutorSSH.py", line 132, in execute
    cmds2, die=die, showout=showout)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 221, in execute
    ch = self.transport.open_session()
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 127, in transport
    if self.client is None:
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 201, in client
    self._connect()
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/ssh/SSHClient.py", line 177, in _connect
    raise j.exceptions.RuntimeError(str(e))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Authentication failed. ((type:runtime.error)
```

**Comment by yveskerwyn** [comment]
verified
