### ISSUE TITLE
js9_config freeze when selcting `YOUR SSH KEY`

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/core9#141]
#### Installation information

- jumpscale version: 9.3.0
- operating system: linux

#### Detailed description
Once we try to edit  `YOUR SSH KEY` the editor freezes

#### Steps to reproduce
open js9_config
use arrow key to try to edit the `YOUR SSH KEY` field

**Comment by zaibon** [comment]
I have more information about the bug. 
It seems that I don't have the micro editor installed in my system.  And editing the SSH field seems to try to open it. So jumspcale tries to download it in the background (without any notification to the user that this is happening, which i find bad, but that's another problem) and fail to do so. 

Here is the stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/js9_config", line 8, in <module>
    j.tools.develop.run()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/develop/DevelopTools.py", line 23, in run
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/apNPSApplication.py", line 30, in run
    return npyssafewrapper.wrapper(self.__remove_argument_call_main)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/npyssafewrapper.py", line 41, in wrapper
    wrapper_no_fork(call_function)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
    return_code = call_function(_SCREEN)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
    return self.main()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/apNPSApplicationManaged.py", line 172, in main
    self._THISFORM.edit()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/fm_form_edit_loop.py", line 86, in edit
    self._widgets__[self.editw].edit()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgtitlefield.py", line 119, in edit
    self.entry_widget.edit()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgtextbox.py", line 383, in edit
    self.get_and_use_key_press()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 610, in get_and_use_key_press
    self.handle_input(ch)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 92, in handle_input
    if self.parent_widget.handle_input(_input):
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 95, in handle_input
    if self.parent.handle_input(_input):
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 80, in handle_input
    self.handlers[_unctrl_input](_input)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgNMenuDisplay.py", line 199, in root_menu
    self._NMDisplay.edit()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgNMenuDisplay.py", line 93, in edit
    _return_value = _fctn(*_args)
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgNMenuDisplay.py", line 39, in _executeSelection
    return sel()
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/muNewMenu.py", line 76, in do
    return self.onSelectFunction(*self.arguments, **self.keywords)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/develop/DevelopConfig.py", line 69, in editConfigFileJS
    j.tools.prefab.local.apps.microeditor.install()
  File "/opt/code/github/jumpscale/prefab9/modules/apps/PrefabMicroEditor.py", line 26, in install
    url=url, to='$TMPDIR/micro/', overwrite=False, retry=3, expand=True, removeTopDir=True)
  File "/opt/code/github/jumpscale/prefab9/modules/network/PrefabTools.py", line 31, in download
    expand=expand,minsizekb=minsizekb,removeTopDir=removeTopDir)
  File "/opt/code/github/jumpscale/prefab9/JumpScale9Prefab/PrefabCore.py", line 562, in file_download
    "Could not download:{}.\nFile size too small after download {}kb.\n".format(url, fsize))
JumpScale9.errorhandling.JSExceptions.RuntimeError: ERROR: Could not download:https://github.com/zyedidia/micro/releases/download/v1.3.3/micro-1.3.3-linux64.tar.gz.
File size too small after download 0kb.
 ((type:runtime.error)
Could not download:https://github.com/zyedidia/micro/releases/download/v1.3.3/micro-1.3.3-linux64.tar.gz.
File size too small after download 0kb.
```

**Comment by andrewayoub** [comment]
can't reproduce
