### ISSUE TITLE
js9 crashes when the user input non-english data to j.sal.fs methods

### ISSUE THREAD

**Issue by islamTaha12** [Jumpscale/core9#168]
**Hint**
It seems an issue in the termianl cause I tried to do it in Tmux and it works fine.

**Description**
If the end user input non-enlgish value to any of j.sal.fs method, JS9 will crash. 

**Example**
Try to do 
```python
j.sal.fs.changeDir('Запомните')
```

**Actual result**
```bash
In [1]: j.sal.fs.changeDir('?????????')
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py", line 1225, in __call__
    self.handler((etype, evalue, etb))
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/ultratb.py", line 1214, in handler
    ostream.write(self.text(etype, evalue, etb))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 915-923: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-61dce1fcfc2d>", line 1, in <module>
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFSDecorators.py", line 126, in wrapper
    if value and validators.intersection({"exists", "file", "dir", "pureFile", "pureDir"}) and not os.path.exists(value):
  File "/usr/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-8: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2927, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 1833, in showtraceback
    self._showtraceback(etype, value, stb)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 1851, in _showtraceback
    print(self.InteractiveTB.stb2text(stb))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 361-369: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/js9", line 23, in <module>
    embed()  # colors='Linux')
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/embed.py", line 386, in embed
    _call_location_id='%s:%s' % (frame.f_code.co_filename, frame.f_lineno))
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/embed.py", line 229, in __call__
    global_ns=global_ns, compile_flags=compile_flags)
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/embed.py", line 324, in mainloop
    self.interact()
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 471, in interact
    self.run_cell(code, store_history=True)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 2875, in run_ast_nodes
    self.showtraceback()
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 1833, in showtraceback
    self._showtraceback(etype, value, stb)
  File "/usr/local/lib/python3.5/dist-packages/IPython/core/interactiveshell.py", line 1851, in _showtraceback
    print(self.InteractiveTB.stb2text(stb))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 915-923: ordinal not in range(128)
root@js9_full:/opt/code/github/core9/tests/jumpscale_test# js9
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
```

**Version**
9.3.0

**Comment by ahmedelsayed-93** [comment]
verified
