### ISSUE TITLE
js9_node sync is not working

### ISSUE THREAD

**Issue by andrewayoub** [Jumpscale/core9#204]
#### Installation information

- jumpscale version: 9.3
- operating system: ubuntu

#### Detailed description

js9_node sync is not working, I'm getting `jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame` error in tmux when I'm trying to execute

js9_node sync -i gw-andrew -m

#### Steps to reproduce

js9_node sync -i gw-andrew -m

#### Relevant stacktraces

```
Traceback (most recent call last):
  File "/usr/local/bin/js9_node", line 152, in <module>
    cli()
  File "/usr/local/bin/js9_node", line 107, in monitor
    node.sync(monitor=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/nodemgr/Node.py", line 234, in sync
    ddirs = self.getActiveCodeDirs()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/nodemgr/Node.py", line 217, in getActiveCodeDirs
    repo = j.clients.git.currentDirGitRepo()
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 32, in currentDirGitRepo
    return self.get(res)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 590, in get
    return GitClient(basedir, check_path=check_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitClient.py", line 51, in __init__
    "jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame ((type:input.error)
jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame
```

**Comment by rkhamis** [comment]
That's how code paths should be indeed. Will close this because it's a requirement of jumpscale architecture
