### ISSUE TITLE
js9_config fails to init a config repo

### ISSUE THREAD

**Issue by xmonader** [Jumpscale/core9#209]
#### Installation information

- jumpscale version:  development branch
core9 ( 51d08f440615d3de75c86d9b2e5728a3d3669542 )
lib9 ( c30fc286ebf25fbe617d0541213f5832d99ecffc )

- operating system: ubuntu 16.04

#### Detailed description
1- js9_code on my config repo `https://github.com/xmonader/jsconfig`
2- switch dir to repo and executing js9_config init fails with 
```JumpScale9.errorhandling.JSExceptions.Input: ERROR: jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame ((type:input.error)```

#### Steps to reproduce
```
root@ahmedheaven:/opt/code/github  # js9_code get --url https://github.com/xmonader/jsconfig

                                                        .,,'
                                                   'c.cool,..',,,,,,,.
                                                  'dxocol:l:;,'......';:,.
                                              .lodoclcccc,...............;:.
                                                ':lc:;;;;;.................:;
            JUMPSCALE                         :oc;'..................,'.....,;
            ---------                        olc'.......'...........,. .,:'..:.
                                            ,oc'......;,',..........od.   'c..'
                                            ;o:......l,   ':........dWkkN. ,;..
                                            .d;.....:K. ;   l'......:KMMM: ''.';'
                                             :,.....cNWNMx  .o.......;OWNc,.....,c
                                              c.....'kMMMX   l.........,,......;'c.
                                             l........xNNx...,. 'coxk;',;;'....;xd.
                                            .l..,...........';;;:dkkc::;;,.....'l'
                                             o'x............lldo,.'o,cl:;'...;,;;
                                           ..;dd'...........':'.,lkkk,.....,.l;l
                                       .',,....'l'.co..;'..........'.....;d,;:
                                    ';;..........;;o:c;,dl;oc,'......';;locc;
                                 ,:;...................;;:',:'',,,,,'.      .,.
                              .::.................................            'c
                            .:,...................................           . .l
                          .:,......................................          'l':
                        .;,.......................................            .l.
                     ';c:.........................................          ;:.';
              ',;::::'...........................................            :d;l;.
           'lolclll,,'..............................','..........            .dccco;
          loooool:,'..............................'l'..........     '.       cocclll..
        .lol:;'...................................::.,,'........    .o     .ldcccccccco:
       ,lcc'.........,;...,;.    ................',c:,''........,.  .o   .;;xccccccccld:
        .';ccc:;;,,'.  ...  ..''..             ;;'...............';.c'.''.  ;loolloooo;
                                ..',,,,,,,''...:o,.................c           ....
                                               .;l.................c.
                                                 ;;;;,'..........,;,
                                                    .':ldddoooddl

* ***Application started***: jscode
* None:pull:ssh://git@github.com/xmonader/jsconfig.git ->/opt/code/github/xmonader/jsconfig
* git clone ssh://git@github.com/xmonader/jsconfig.git -> /opt/code/github/xmonader/jsconfig
* mkdir -p /opt/code/github/xmonader;cd /opt/code/github/xmonader;git -c http.sslVerify=false clone   ssh://git@github.com/xmonader/jsconfig.git /opt/code/github/xmonader/jsconfig
root@ahmedheaven:/opt/code/github  # cd xmonader/jsconfig 
root@ahmedheaven:/opt/code/github/xmonader/jsconfig  git:(master) # ls
root@ahmedheaven:/opt/code/github/xmonader/jsconfig  git:(master) # js9_config init
* JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
* JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/js9_config", line 84, in <module>
    cli()
  File "/usr/local/bin/js9_config", line 26, in init
    j.tools.configmanager.init(silent=silent, configpath=path, keypath=key)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/ConfigManager.py", line 415, in init
    cpath, giturl = self._findConfigRepo(die=False)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/ConfigManager.py", line 171, in _findConfigRepo
    g = j.clients.git.get(cpath)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/git/GitFactory.py", line 590, in get
    return GitClient(basedir, check_path=check_path)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/git/GitClient.py", line 51, in __init__
    "jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame ((type:input.error)
jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame
root@ahmedheaven:/opt/code/github/xmonader/jsconfig  git:(master) # mv .git/ dmdm
root@ahmedheaven:/opt/code/github/xmonader/jsconfig  # js9_config init
* JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
* JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/js9_config", line 84, in <module>
    cli()
  File "/usr/local/bin/js9_config", line 26, in init
    j.tools.configmanager.init(silent=silent, configpath=path, keypath=key)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/ConfigManager.py", line 415, in init
    cpath, giturl = self._findConfigRepo(die=False)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/ConfigManager.py", line 171, in _findConfigRepo
    g = j.clients.git.get(cpath)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/git/GitFactory.py", line 590, in get
    return GitClient(basedir, check_path=check_path)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/git/GitClient.py", line 51, in __init__
    "jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame ((type:input.error)
jumpscale code management always requires path in form of $somewhere/code/$type/$`
```

**Comment by rkhamis** [comment]
The error explains it all here:
`jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame `

meaning your repo should be under `{codedir}/github/xmonader/jsconfig`

**Comment by rkhamis** [comment]
No, seems pwd is indeed fine.

**Comment by xmonader** [comment]
problem was due to having itenv_test 
```
> /opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitClient.py(49)__init__()
     48             import ipdb; ipdb.set_trace()
---> 49             if not base.startswith('cockpit'):
     50                 if base.count("/") != 2:

ipdb> base
'github/itenv_test'

```
And fixed after moving it to another place
