### ISSUE TITLE
js9_config init fails on valid path

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#217]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu on ch-gen-1

#### Detailed description

`js9_config init` doesn't accept path `/opt/code/docs/yves/myconfig` as a valid path for a configuration repository,.

#### Steps to reproduce

```python
mkdir -p /opt/code/docs/yves/myconfig
cd /opt/code/docs/yves/myconfig
js9_config init
```

#### Relevant stacktraces

```python
[Tue20 11:16] - ConfigManager.py  :337 :j.tools.configmanager - INFO     - JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
Traceback (most recent call last):
  File "/usr/local/bin/js9_config", line 92, in <module>
    cli()
  File "/usr/local/bin/js9_config", line 33, in init
    j.tools.configmanager.init(silent=silent, configpath=path, keypath=key)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 412, in init
    ssh_init(ssh_silent=silent)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 368, in ssh_init
    j.clients.sshkey.key_load(path=keys[0])
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKeys.py", line 75, in key_load
    return self.get(instance=name)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKey.py", line 23, in __init__
    parent=parent, template=TEMPLATE, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfig.py", line 29, in __init__
    self, instance=self._instance, data=data, template=self._template, ui=self._ui)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 224, in _get_for_obj
    sc = Config(instance=instance, location=location, template=template, data=data)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 22, in __init__
    if not j.sal.fs.exists(self.path):
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 59, in path
    self._path = j.sal.fs.joinPaths(j.tools.configmanager.path, self.location, self.instance + '.toml')
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 64, in path
    self.init()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 420, in init
    cpath, giturl = self._findConfigRepo(die=False)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 174, in _findConfigRepo
    g = j.clients.git.get(cpath)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 593, in get
    return GitClient(basedir, check_path=check_path)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitClient.py", line 51, in __init__
    "jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame")
JumpScale9.errorhandling.JSExceptions.Input: ERROR: jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame ((type:input.error)
[Tue20 11:16] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - jumpscale code management always requires path in form of $somewhere/code/$type/$account/$reponame
```

**Comment by ahussein** [comment]
fixed on development branch
@yveskerwyn will verify
