### ISSUE TITLE
js9_config reset -f => unexpected JS9 init questions + error

### ISSUE THREAD

**Issue by yveskerwyn** [Jumpscale/core9#218]
#### Installation information

- jumpscale version: 9.3.0
- operating system: Ubuntu VM

See tmux session, window 1:
```
ssh root@185.15.201.111 -p7922
```

#### Detailed description

Executing `js9_config reset -f` is supposed to reset without asking questions.

In my case I got the JS9 init questions:
```bash
JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
JS9 init: Do you want to use a git based CONFIG dir, y/n?
 [y/n]: y
JS9 init: Specify a url like: 'ssh://git@docs.grid.tf:7022/despiegk/config_despiegk.git'
url:
```

Replying y, y, enter results in `RuntimeError: dest cannot be None (url is also '')`

#### Steps to reproduce

```
js9_config reset -f
```

#### Relevant stacktraces

```python
root@vm-941:/opt/code/docs/yves# js9_config reset -f
[Wed21 09:43] - BashFactory.py    :213 :j.profile            - DEBUG    - WARNING: locale has been fixed, please do: `source ~/.profile_js`
[Wed21 09:43] - BashFactory.py    :178 :j.profile            - DEBUG    - INCLUDE IN DEFAULT PROFILE:/root/.profile_js
[Wed21 09:43] - ConfigManager.py  :394 :j.tools.configmanager - DEBUG    - init: silent:False path: nodata

[Wed21 09:43] - ConfigManager.py  :347 :j.tools.configmanager - DEBUG    - ssh init (no keypath specified)
[Wed21 09:43] - ConfigManager.py  :354 :j.tools.configmanager - INFO     - found 0 keys from ssh-agent
[Wed21 09:43] - SystemProcess.py  :86  :j.sal.process        - DEBUG    - execute:ssh-add -l
[Wed21 09:43] - SystemProcess.py  :195 :j.sal.process        - DEBUG    - system.process.run stdout:
2048 SHA256:9d1GC+N9perI5vCSYikG+zsWcclVSKArp9H8ZD1W3PE /root/.ssh/id_rsa (RSA)

[Wed21 09:43] - Config.py         :57  :j.config             - DEBUG    - init getpath:None
[Wed21 09:43] - ConfigManager.py  :394 :j.tools.configmanager - DEBUG    - init: silent:False path: nodata

[Wed21 09:43] - ConfigManager.py  :347 :j.tools.configmanager - DEBUG    - ssh init (no keypath specified)
[Wed21 09:43] - ConfigManager.py  :337 :j.tools.configmanager - INFO     - JS9 init: ssh key found in agent is:'/root/.ssh/id_rsa'
[Wed21 09:43] - ConfigManager.py  :337 :j.tools.configmanager - INFO     - JS9 init: Is it ok to use this one:'/root/.ssh/id_rsa'?
 [y/n]: y
 Wed21 09:43] - ConfigManager.py  :337 :j.tools.configmanager - INFO     - JS9 init: Do you want to use a git based CONFIG dir, y/n?
 [y/n]: y
 [Wed21 09:43] - ConfigManager.py  :337 :j.tools.configmanager - INFO     - JS9 init: Specify a url like: 'ssh://git@docs.grid.tf:7022/despiegk/config_despiegk.git'
url:
Traceback (most recent call last):
  File "/usr/local/bin/js9_config", line 92, in <module>
    cli()
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/bin/js9_config", line 51, in reset
    j.tools.configmanager.reset(location=location, instance=instance, force=force)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 45, in reset
    path = self.path
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 64, in path
    self.init()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 412, in init
    ssh_init(ssh_silent=silent)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 368, in ssh_init
    j.clients.sshkey.key_load(path=keys[0])
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKeys.py", line 75, in key_load
    return self.get(instance=name, data={'path': path})
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKey.py", line 23, in __init__
    parent=parent, template=TEMPLATE, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfig.py", line 29, in __init__
    self, instance=self._instance, data=data, template=self._template, ui=self._ui)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 224, in _get_for_obj
    sc = Config(instance=instance, location=location, template=template, data=data)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 22, in __init__
    if not j.sal.fs.exists(self.path):
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/Config.py", line 59, in path
    self._path = j.sal.fs.joinPaths(j.tools.configmanager.path, self.location, self.instance + '.toml')
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 64, in path
    self.init()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 447, in init
    cpath = j.clients.git.pullGitRepo(url=giturl, interactive=True, ssh=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 308, in pullGitRepo
    url, dest, login, passwd, reset=reset, ssh=ssh, codeDir=codeDir, executor=executor)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/git/GitFactory.py", line 184, in getGitRepoArgs
    raise RuntimeError("dest cannot be None (url is also '')")
RuntimeError: dest cannot be None (url is also '')
[Wed21 09:43] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - dest cannot be None (url is also '')
```

**Comment by ahussein** [comment]
This is fixed on development

**Comment by yveskerwyn** [comment]
verified
