### ISSUE TITLE
usage example (j.application.getMemoryUsage) is broken: psutil version might need to be updated

### ISSUE THREAD

**Issue by iwanbk** [Jumpscale/core9#226]
0-robot needs psutil 5.4.3 while JS9 install psutil 3.4.2

https://github.com/zero-os/0-robot/blob/21d33aaf56e3a287eda5f7b6751bb4ea4a0c24f3/setup.py#L61-L63

#### Installation information

- jumpscale version: latest development branch 31592bbc5c6469dbbc111b287a1c00b655d6bc23 
- operating system: ubuntu 16.04

#### Detailed description

Successfully installed the js9, but failed to execute usage example 
```
 python3 -c 'from js9 import j;print(j.application.getMemoryUsage())'
```
as described at https://github.com/Jumpscale/core9/blob/development/README.md#usage

#### Steps to reproduce

Install JS9
```
export JS9BRANCH="development"
curl https://raw.githubusercontent.com/Jumpscale/core9/$JS9BRANCH/install.sh?$RANDOM > /tmp/install_js9.sh;bash /tmp/install_js9.sh
```
test that js9 works
```python
root@robo:~# js9
* ***Application started***: jsshell
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
```

execute the example
```python
root@robo:~# python3 -c 'from js9 import j;print(j.application.getMemoryUsage())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/Application.py", line 187, in getMemoryUsage
    info = p.memory_full_info()
AttributeError: 'Process' object has no attribute 'memory_full_info'
[Wed18 11:04] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 'Process' object has no attribute 'memory_full_info'
```

#### Relevant stacktraces

```python
root@robo:~# python3 -c 'from js9 import j;print(j.application.getMemoryUsage())'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/code/github/jumpscale/core9/JumpScale9/core/Application.py", line 187, in getMemoryUsage
    info = p.memory_full_info()
AttributeError: 'Process' object has no attribute 'memory_full_info'
[Wed18 11:04] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 'Process' object has no attribute 'memory_full_info'
```

psutil version = 3.4.2
```python
root@robo:~# pip freeze | grep psutil
psutil==3.4.2
```

**Comment by iwanbk** [comment]
Simply modifying `psutil` version in `setup.py` didn't fix the issue.

I made a workaround by installing `psutil` (5.4.5) first before installing this library

**Comment by iwanbk** [comment]
> Simply modifying psutil version in setup.py didn't fix the issue.

It seems the fix is the same as what i've tried.
https://github.com/Jumpscale/core9/commit/8936c330a6322a3a411f61d38a327cff2a12facc

Really wonder why it didn't succeed
