### ISSUE TITLE
js9_init is broken

### ISSUE THREAD

**Issue by ashraffouda** [Jumpscale/core9#232]
#### Installation information
I'm using jumpscale from development branch 

#### Detailed description
after updating core9, lib9, prefab 
I got these errros when I executed js9_init
```
Traceback (most recent call last):
  File "/usr/local/bin/js9_init", line 22, in <module>
    j.tools.jsloader.generate()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 462, in generate
    createdir=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 217, in copyDirTree
    overwriteFiles=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 217, in copyDirTree
    overwriteFiles=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 221, in copyDirTree
    srcname, dstname, createDirIfNeeded=False, overwriteFile=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFSDecorators.py", line 155, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 44, in copyFile
    if os.path.samefile(fileFrom, to):
  File "/usr/lib/python3.5/genericpath.py", line 91, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/host/autocomplete/JumpScale9Lib/clients/zero_os/RTInfoManager.py'
```
and this 
```
Traceback (most recent call last):
  File "/usr/local/bin/js9_init", line 22, in <module>
    j.tools.jsloader.generate()
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 462, in generate
    createdir=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 217, in copyDirTree
    overwriteFiles=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 217, in copyDirTree
    overwriteFiles=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 217, in copyDirTree
    overwriteFiles=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 221, in copyDirTree
    srcname, dstname, createDirIfNeeded=False, overwriteFile=overwriteFiles)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFSDecorators.py", line 155, in wrapper
    return func(*args, **kwargs)
  File "/opt/code/github/jumpscale/core9/JumpScale9/fs/SystemFS.py", line 44, in copyFile
    if os.path.samefile(fileFrom, to):
  File "/usr/lib/python3.5/genericpath.py", line 91, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/host/autocomplete/JumpScale9Lib/data/encryption/mnemonic/__init__.py'
[Sun27 08:41] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - [Errno 2] No such file or directory: '/host/autocomplete/JumpScale9Lib/data/encryption/mnemonic/__init__.py'

```

**Comment by ashraffouda** [comment]
fixed
