### ISSUE TITLE
js installation from development branch is broken

### ISSUE THREAD

**Issue by john-kheir** [Jumpscale/core9#240]
#### Installation information
 

- jumpscale version: development
- operating system: ubuntu 16

#### Detailed description
```
  export ZUTILSBRANCH=development
  export JS9BRANCH=development
  curl https://raw.githubusercontent.com/Jumpscale/bash/${ZUTILSBRANCH}/install.sh?$RANDOM > /tmp/install.sh;bash /tmp/install.sh
   . ~/.bashrc
   ZInstall_host_js99

```

##### Error
```
    
    Installed /opt/code/github/jumpscale/core9
    Running post install task
    /usr/local/lib/python3.5/dist-packages/setuptools/dist.py:398: UserWarning: Normalizing '9.4.0-rc4' to '9.4.0rc4'
      normalized_version,
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 95, in <module>
        'cmds/js9_doc',
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/opt/code/github/jumpscale/core9/setup.py", line 34, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/opt/code/github/jumpscale/core9/setup.py", line 9, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/opt/code/github/jumpscale/core9/JumpScale9/__init__.py", line 132, in <module>
        from .data.text.Text import Text
      File "/opt/code/github/jumpscale/core9/JumpScale9/data/text/Text.py", line 9, in <module>
        from unidecode import unidecode
    ImportError: No module named 'unidecode'
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/opt/code/github/jumpscale/core9/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /opt/code/github/jumpscale/core9/

[-] something went wrong: Could not install core9 of js9


```

**Comment by ahussein** [comment]
fixed on development: https://travis-ci.org/Jumpscale/core9/builds/399481310

**Comment by john-kheir** [comment]
```
export ZUTILSBRANCH=development
export JS9BRANCH=development
curl https://raw.githubusercontent.com/Jumpscale/bash/${ZUTILSBRANCH}/install.sh?$RANDOM > /tmp/install.sh;bash /tmp/install.sh
 . ~/.bashrc
 ZInstall_host_js9_full
```
