### ISSUE TITLE
jumpscale9 installation issues: PIP + BASH

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/core9#56]
#### Installation information

- jumpscale version:
core9 -- Master branch
- operating system:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

#### Steps to reproduce

sudo pip3 install git+https://github.com/Jumpscale/core9@master
```
    Running post install task
    config set redis:{'port': 6379, 'addr': 'localhost'}
    config set me:{'loginname': 'despiegk', 'fullname': 'Kristof De Spiegeleer'}
    config set git:{'ays': {'url': 'https://github.com/Jumpscale/ays9.git', 'branch': 'master'}, 'js': {'url': 'https://github.com/Jumpscale/core9.git', 'branch': 'master'}}
    config set grid:{'gid': 0, 'nid': 0}
    config set email:{'smtp_server': '', 'smtp_port': 443, 'from': 'info@incubaid.com'}
    config set dirs:{'VARDIR': '/home/rmh/gig/var/', 'CODEDIR': '/home/rmh/gig/code', 'HOMEDIR': '/home/rmh', 'BINDIR': '/home/rmh/gig/gig/bin', 'TMPDIR': '/tmp', 'CFGDIR': '/home/rmh/gig/var/cfg', 'LIBDIR': '/home/rmh/gig/gig/lib', 'DATADIR': '/home/rmh/gig/var/data', 'BUILDDIR': '/home/rmh/gig/var/build', 'BASEDIR': '/home/rmh/gig/gig', 'TEMPLATEDIR': '/home/rmh/gig/gig/templates', 'LOGDIR': '/home/rmh/gig/var/log', 'JSAPPSDIR': '/home/rmh/gig/gig/apps'}
    config set system:{'debug': True, 'autopip': False, 'container': False, 'readonly': False}
    config set ssh:{'SSHKEYNAME': 'id_rsa'}
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ivqvafu6-build/setup.py", line 88, in <module>
        'cmds/js9_docs',
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-ivqvafu6-build/setup.py", line 25, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/tmp/pip-ivqvafu6-build/setup.py", line 9, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/tmp/pip-ivqvafu6-build/JumpScale9/__init__.py", line 100, in <module>
        j.do.initEnv()
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 2138, in initEnv
        self.linkJSCommandsToSystem()
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 2142, in linkJSCommandsToSystem
        self.symlinkFilesInDir(src, "/usr/local/bin", delete=True, includeDirs=False, makeExecutable=True)
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 1238, in symlinkFilesInDir
        listSymlinks=True)
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 1432, in listFilesInDir
        case_sensitivity=case_sensitivity, exclude=exclude, followSymlinks=followSymlinks, listSymlinks=listSymlinks)
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 1492, in _listAllInDir
        dircontent = self._listInDir(path)
      File "/tmp/pip-ivqvafu6-build/JumpScale9/core/InstallTools.py", line 1354, in _listInDir
        path)
    RuntimeError: Specified path: /home/rmh/gig/code/github/jumpscale/core9/cmds/ does not exist in system.fs.listDir
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ivqvafu6-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kzs9bvyc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ivqvafu6-build/
```
Also:

bash -x install.sh

````
 bash -x install.sh 
+ pip3 install -e .
Obtaining file:///home/rmh/ays9
Requirement already satisfied: JumpScale9>=9.1.1 in /usr/local/lib/python3.5/dist-packages (from JumpScale9AYS==9.1.1)
Collecting JumpScale9Lib>=9.1.1 (from JumpScale9AYS==9.1.1)
  Could not find a version that satisfies the requirement JumpScale9Lib>=9.1.1 (from JumpScale9AYS==9.1.1) (from versions: )
No matching distribution found for JumpScale9Lib>=9.1.1 (from JumpScale9AYS==9.1.1)
````

**Comment by rainmanh** [comment]
# Rel to *PIP3*

Only way to manually fix it locally:

```
mkdir /<dir>/gig/code/github/jumpscale/core9/cmds/
```
And better to use something like:
````
pip3 install --install-option="--prefix=/opt/core9" git+https://github.com/Jumpscale/core9@master
````

Otherwise that's dropping all the checkout into the tmp (not the best place for it...)

Many thanks guys...

**Comment by rkhamis** [comment]
@rainmanh thanks a lot for this. I'll make sure to clean it up!
