### ISSUE TITLE
pip3 install git+https://github.com/Jumpscale/core9@master -- breaks

### ISSUE THREAD

**Issue by rainmanh** [Jumpscale/core9#61]
#### Installation information

- jumpscale version:

core9@master

- operating system:

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

#### Detailed description

pip3 fails to intall Jumpscale from git

#### Steps to reproduce

````
 pip3 install git+https://github.com/Jumpscale/core9@master
````

#### Relevant stacktraces

```
   byte-compiling /usr/local/lib/python3.5/dist-packages/JumpScale9/fs/__init__.py to __init__.cpython-35.pyc
    byte-compiling /usr/local/lib/python3.5/dist-packages/JumpScale9/__init__.py to __init__.cpython-35.pyc
    byte-compiling /usr/local/lib/python3.5/dist-packages/install/dependencies.py to dependencies.cpython-35.pyc
    byte-compiling /usr/local/lib/python3.5/dist-packages/install/bootstrap.py to bootstrap.cpython-35.pyc
    byte-compiling /usr/local/lib/python3.5/dist-packages/install/__init__.py to __init__.cpython-35.pyc
    running install_egg_info
    running egg_info
    creating JumpScale9.egg-info
    writing requirements to JumpScale9.egg-info/requires.txt
    writing top-level names to JumpScale9.egg-info/top_level.txt
    writing dependency_links to JumpScale9.egg-info/dependency_links.txt
    writing JumpScale9.egg-info/PKG-INFO
    writing manifest file 'JumpScale9.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'JumpScale9.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'JumpScale9.egg-info/SOURCES.txt'
    Copying JumpScale9.egg-info to /usr/local/lib/python3.5/dist-packages/JumpScale9-9.1.1.egg-info
    running install_scripts
    copying build/scripts-3.5/js9_code -> /usr/local/bin
    copying build/scripts-3.5/js9_docs -> /usr/local/bin
    copying build/scripts-3.5/js9_docker -> /usr/local/bin
    copying build/scripts-3.5/js9 -> /usr/local/bin
    changing mode of /usr/local/bin/js9_code to 755
    changing mode of /usr/local/bin/js9_docs to 755
    changing mode of /usr/local/bin/js9_docker to 755
    changing mode of /usr/local/bin/js9 to 755
    writing list of installed files to '/tmp/pip-r8tdmtn5-record/install-record.txt'
    Running post install task
    config set dirs:{'CODEDIR': '/root/gig/code', 'BINDIR': '/root/gig/gig/bin', 'TMPDIR': '/tmp', 'TEMPLATEDIR': '/root/gig/gig/templates', 'BASEDIR': '/root/gig/gig', 'BUILDDIR': '/root/gig/var/build', 'LIBDIR': '/root/gig/gig/lib', 'LOGDIR': '/root/gig/var/log', 'VARDIR': '/root/gig/var/', 'JSAPPSDIR': '/root/gig/gig/apps', 'HOMEDIR': '/root', 'CFGDIR': '/root/gig/var/cfg', 'DATADIR': '/root/gig/var/data'}
    config set redis:{'addr': 'localhost', 'port': 6379}
    config set system:{'debug': True, 'readonly': False, 'container': False, 'autopip': False}
    config set grid:{'gid': 0, 'nid': 0}
    config set email:{'from': 'info@incubaid.com', 'smtp_server': '', 'smtp_port': 443}
    config set ssh:{'SSHKEYNAME': 'id_rsa'}
    config set git:{'ays': {'branch': 'master', 'url': 'https://github.com/Jumpscale/ays9.git'}, 'js': {'branch': 'master', 'url': 'https://github.com/Jumpscale/core9.git'}}
    config set me:{'loginname': 'despiegk', 'fullname': 'Kristof De Spiegeleer'}
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ezuidrsf-build/setup.py", line 88, in <module>
        'cmds/js9_docs',
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-ezuidrsf-build/setup.py", line 25, in run
        self.execute(_post_install, (libname, libpath), msg="Running post install task")
      File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
        func(*args)
      File "/tmp/pip-ezuidrsf-build/setup.py", line 9, in _post_install
        from JumpScale9 import j  # here its still the boostrap JumpScale9
      File "/tmp/pip-ezuidrsf-build/JumpScale9/__init__.py", line 100, in <module>
        j.do.initEnv()
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 2138, in initEnv
        self.linkJSCommandsToSystem()
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 2142, in linkJSCommandsToSystem
        self.symlinkFilesInDir(src, "/usr/local/bin", delete=True, includeDirs=False, makeExecutable=True)
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 1238, in symlinkFilesInDir
        listSymlinks=True)
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 1432, in listFilesInDir
        case_sensitivity=case_sensitivity, exclude=exclude, followSymlinks=followSymlinks, listSymlinks=listSymlinks)
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 1492, in _listAllInDir
        dircontent = self._listInDir(path)
      File "/tmp/pip-ezuidrsf-build/JumpScale9/core/InstallTools.py", line 1354, in _listInDir
        path)
    RuntimeError: Specified path: /root/gig/code/github/jumpscale/core9/cmds/ does not exist in system.fs.listDir
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-ezuidrsf-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-r8tdmtn5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-ezuidrsf-build/
```

**Comment by BolaNasr** [comment]
> pip3 install git+https://github.com/Jumpscale/core9@master

 
it's working correctly
